CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    document VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    type VARCHAR(50) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(30),
    classification VARCHAR(80),
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_customer_document UNIQUE (document)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    fabric_type VARCHAR(100) NOT NULL,
    composition VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_product_code UNIQUE (code)
);

CREATE TABLE unit_of_measure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_unit_of_measure_code UNIQUE (code)
);

CREATE TABLE product_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    product_id BIGINT NOT NULL,
    sku VARCHAR(60) NOT NULL,
    color VARCHAR(80) NOT NULL,
    pattern VARCHAR(120),
    width NUMERIC(12, 3) NOT NULL,
    unit_id BIGINT NOT NULL,
    cost NUMERIC(19, 2) NOT NULL,
    sale_price NUMERIC(19, 2) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_product_variant_sku UNIQUE (sku),
    CONSTRAINT fk_variant_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT fk_variant_unit FOREIGN KEY (unit_id) REFERENCES unit_of_measure (id)
);

CREATE INDEX idx_product_variant_product ON product_variant (product_id);
CREATE INDEX idx_product_variant_unit ON product_variant (unit_id);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_refresh_token_hash ON refresh_token (token_hash);
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at TIMESTAMP WITH TIME ZONE NOT NULL,
    username VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    entity VARCHAR(255) NOT NULL,
    entity_id BIGINT,
    details VARCHAR(1500) NOT NULL,
    ip VARCHAR(255),
    success BOOLEAN NOT NULL
);

CREATE INDEX idx_audit_event_at ON audit_event (at DESC, id DESC);
