CREATE TABLE inventory_balance (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                   updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                   variant_id BIGINT NOT NULL,
                                   warehouse_id BIGINT NOT NULL,
                                   available_quantity NUMERIC(19,3) NOT NULL DEFAULT 0,
                                   reserved_quantity NUMERIC(19,3) NOT NULL DEFAULT 0,
                                   minimum_quantity NUMERIC(19,3) NOT NULL DEFAULT 0,
                                   CONSTRAINT uk_inventory_balance_variant_warehouse UNIQUE (variant_id, warehouse_id),
                                   CONSTRAINT fk_inventory_balance_variant
                                       FOREIGN KEY (variant_id) REFERENCES product_variant(id),
                                   CONSTRAINT fk_inventory_balance_warehouse
                                       FOREIGN KEY (warehouse_id) REFERENCES warehouse(id)
);

CREATE INDEX idx_inventory_balance_variant
    ON inventory_balance (variant_id);

CREATE INDEX idx_inventory_balance_warehouse
    ON inventory_balance (warehouse_id);
