CREATE TABLE inventory_movement (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                    variant_id BIGINT NOT NULL,
                                    warehouse_id BIGINT NOT NULL,
                                    movement_type VARCHAR(40) NOT NULL,
                                    quantity NUMERIC(19,3) NOT NULL,
                                    reserved_delta NUMERIC(19,3) NOT NULL DEFAULT 0,
                                    previous_available NUMERIC(19,3) NOT NULL,
                                    new_available NUMERIC(19,3) NOT NULL,
                                    previous_reserved NUMERIC(19,3) NOT NULL,
                                    new_reserved NUMERIC(19,3) NOT NULL,
                                    source_document VARCHAR(255) NOT NULL,
                                    performed_by VARCHAR(255) NOT NULL,
                                    movement_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                    reason VARCHAR(500),
                                    compensates_movement_id BIGINT,
                                    CONSTRAINT fk_inventory_movement_variant
                                        FOREIGN KEY (variant_id) REFERENCES product_variant(id),
                                    CONSTRAINT fk_inventory_movement_warehouse
                                        FOREIGN KEY (warehouse_id) REFERENCES warehouse(id),
                                    CONSTRAINT fk_inventory_movement_compensates
                                        FOREIGN KEY (compensates_movement_id) REFERENCES inventory_movement(id),
                                    CONSTRAINT uk_inventory_movement_compensates UNIQUE (compensates_movement_id),
                                    CONSTRAINT ck_inventory_movement_available_balance
                                        CHECK (new_available - previous_available = quantity),
                                    CONSTRAINT ck_inventory_movement_reserved_balance
                                        CHECK (new_reserved - previous_reserved = reserved_delta),
                                    CONSTRAINT ck_inventory_movement_type
                                        CHECK (movement_type IN ('SALE', 'RECEIPT', 'ADJUSTMENT', 'COMPENSATION')),
                                    CONSTRAINT ck_inventory_movement_nature
                                        CHECK (
                                            (movement_type <> 'SALE' OR quantity < 0)
                                                AND (movement_type <> 'RECEIPT' OR quantity > 0)
                                            )
);

CREATE INDEX idx_inventory_movement_date
    ON inventory_movement (movement_at);

CREATE INDEX idx_inventory_movement_variant
    ON inventory_movement (variant_id);

CREATE INDEX idx_inventory_movement_warehouse
    ON inventory_movement (warehouse_id);

CREATE INDEX idx_inventory_movement_type
    ON inventory_movement (movement_type);

CREATE INDEX idx_inventory_movement_document
    ON inventory_movement (source_document);
